- name: Compile workshop.txt file
  template:
    src: workshop.txt.j2
    dest: "{{ quakelive_home }}/baseq3/workshop.txt"
    owner: "{{ quakelive_user }}"
    group: "{{ quakelive_user }}"
    mode: 0660
  notify: restart_quakelive

- name: Compile server.cfg file
  template:
    src: server.cfg.j2
    dest: "{{ quakelive_home }}/baseq3/server.cfg"
    owner: "{{ quakelive_user }}"
    group: "{{ quakelive_user }}"
    mode: 0660
  notify: restart_quakelive

- name: Compile access.txt file
  template:
    src: access.txt.j2
    dest: "{{ quakelive_home }}/baseq3/access.txt"
    owner: "{{ quakelive_user }}"
    group: "{{ quakelive_user }}"
    mode: 0660
  notify: restart_quakelive

- name: Place all mappool files
  copy:
    src: mappools/
    dest: "{{ quakelive_home }}/baseq3"
  notify: restart_quakelive
