- name: Install wicked-minqlx-plugins
  git:
    repo: https://github.com/flazzarini/wicked-minqlx-plugins
    dest: "{{ quakelive_home }}/wicked-minqlx-plugins"
  become: true
  become_user: "{{ quakelive_user }}"

- name: "Copy plugins into {{ quakelive_home }}/minqlx-plugins"
  copy:
    remote_src: true
    src: "{{ quakelive_home }}/wicked-minqlx-plugins/{{ item }}"
    dest: "{{ quakelive_home }}/minqlx-plugins/{{ item }}"
    owner: "{{ quakelive_user }}"
  loop:
    - "wickedplayerdies.py"
    - "wickedshout.py"
  notify: restart_quakelive
