---

- name: quakelive_update_cache
  apt:
    update_cache: "yes"

- name: reread_supervisor
  supervisorctl:
    name: quakelive
    state: present

- name: restart_quakelive
  supervisorctl:
    state: restarted
    name: quakelive

# handlers file for ansible-quakelive
