---

- name: quakelive_update_cache
  apt:
    update_cache: "yes"

- name: reread_supervisor
  shell: supervisorctl reread && supervisorctl update

- name: restart_quakelive
  shell: supervisorctl restart quakelive


# handlers file for ansible-quakelive
